USERNAME = "root"
PASSWORD = "root"
HOST = "db"
DATABASE = "PIIP_pruebas"
# DATABASE = "PIIP"

"""
USERNAME = "admin"
PASSWORD = "*&WcgpYU4-.{mt.-"
HOST = "127.0.0.1"
"""

SECRET_KEY = "hola"
SECURITY_PASSWORD_SALT = "mundo"
MAIL_DEFAULT_SENDER = "piip.ipn.noreply.secure@gmail.com"
